### PR TITLE
Added download popup for gifs.

### PR DESCRIPTION
**Pull request by Firstbober**
Added feature requested in issue #12

### CODE REVIEW

**Comment by im-ankitjais** [comment]
Awsome job @Firstbober . I liked the popup alert styling. But on clicking "yes" the image is not downloading , instead it goes to new tab and clicking on it goes to giphy site. I want that it directly start downloading when clicked on "yes".  Please try to fix.

**Comment by Firstbober** [comment]
@tekgeek88 written a good logic to download which should work with my alert box but I don't know how to combine it to make both PRs merged. I'm referring to #15. The only thing I can think of is to make a skeleton with he's download function and then he's code will be merged.

**Comment by im-ankitjais** [comment]
Yeh. also can you try this -> in #15 when image is clicked what functions are working you can put that in your "yes" option? Is it possible?

**Comment by Firstbober** [comment]
Yes, tomorrow I try to do this.

**Comment by Firstbober** [comment]
I've managed to connect download function in #15 with "yes" option in my alert box! I will commit the code with function name and later all logic from #15 should be merged.

**Comment by im-ankitjais** [comment]
Merged..!! Go ahead to add logic on Yes option.

**Comment by Firstbober** [comment]
All the logic is in #15 and that PR should be merged as well after removing "onclick" from `pushToDOM` function. I don't want to steal someone code. I only used function to call all of this code from @tekgeek88 PR.

**Pull request merged**
